#working directory i.e. parent directory where the results are written
workdir: "/proj/sllstore2017028/nobackup/nbis4067/results/data2018/april2018/"

# Data path
datadir: ""


# Output paths
resdir: "results/"
logdir: "logdir/"
# Snakefile location
snkpth: "/Snakefile_piRNA_full"
# location of /src directory with auxiliary scripts for data summarisation and plotting
srcpth: ""

# Indices and reference files
ENS_GENOME_FA: "/proj/sllstore2017028/nobackup/nbis4067/reference/ensembl/Drosophila_melanogaster.BDGP6.22.dna.toplevel.fa"
ENS_GTF: "/proj/sllstore2017028/nobackup/nbis4067/reference/ensembl/Drosophila_melanogaster.BDGP6.22.96.dm6_RepearMasker.gtf"
REPEATMASKER_GTF: "/proj/sllstore2017028/nobackup/nbis4067/reference/ensembl/dm6.RepeatMasker.ensembl.biotype.repfam.gtf"

#this will be removed when NGS Toolbox is available as a conda module
#NGSTB_PTH: "/home/agata/soft/protrac/TBr2"
NGSTB_PTH: ""
