channels:
  - bioconda
  - conda-forge
  - defaults
dependencies:
  - snakemake=5.5.0
  - graphviz=2.40.1
  - xorg-libxrender
  - xorg-libxpm
  - ordered-set
  - python=3.5
  - fastqc=0.11.8
  - samtools=1.9
  - cutadapt=1.18
  - bowtie=1.2.2
  - multiqc=1.7
  - protrac=2.4.2
  - r=3.6.0
  - r-ggplot2=3.1.1
  - r-reshape2=1.4.3
  - r-optparse=1.6.1
  